window.RAFD_DATA = {
 "n_frames": 16,
 "menu": [
  "success",
  "pick",
  "drop",
  "place",
  "release"
 ],
 "clips": [
  {
   "key": "sim__case_000002__perfect",
   "source": "Simulation",
   "title": "Sim \u00b7 clean pick-and-place",
   "gt_word": "success",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.947,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__perfect/frame_00.png",
    "clips/sim__case_000002__perfect/frame_01.png",
    "clips/sim__case_000002__perfect/frame_02.png",
    "clips/sim__case_000002__perfect/frame_03.png",
    "clips/sim__case_000002__perfect/frame_04.png",
    "clips/sim__case_000002__perfect/frame_05.png",
    "clips/sim__case_000002__perfect/frame_06.png",
    "clips/sim__case_000002__perfect/frame_07.png",
    "clips/sim__case_000002__perfect/frame_08.png",
    "clips/sim__case_000002__perfect/frame_09.png",
    "clips/sim__case_000002__perfect/frame_10.png",
    "clips/sim__case_000002__perfect/frame_11.png",
    "clips/sim__case_000002__perfect/frame_12.png",
    "clips/sim__case_000002__perfect/frame_13.png",
    "clips/sim__case_000002__perfect/frame_14.png",
    "clips/sim__case_000002__perfect/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__perfect/clip.gif"
  },
  {
   "key": "sim__case_000002__fail_pick",
   "source": "Simulation",
   "title": "Sim \u00b7 failed pick",
   "gt_word": "pick",
   "pred_word": "pick",
   "ok": false,
   "head": "FAILURE \u00b7 PICK",
   "body": "The arm failed to pick up the object (missed or off-centre grasp).",
   "conf": 0.992,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__fail_pick/frame_00.png",
    "clips/sim__case_000002__fail_pick/frame_01.png",
    "clips/sim__case_000002__fail_pick/frame_02.png",
    "clips/sim__case_000002__fail_pick/frame_03.png",
    "clips/sim__case_000002__fail_pick/frame_04.png",
    "clips/sim__case_000002__fail_pick/frame_05.png",
    "clips/sim__case_000002__fail_pick/frame_06.png",
    "clips/sim__case_000002__fail_pick/frame_07.png",
    "clips/sim__case_000002__fail_pick/frame_08.png",
    "clips/sim__case_000002__fail_pick/frame_09.png",
    "clips/sim__case_000002__fail_pick/frame_10.png",
    "clips/sim__case_000002__fail_pick/frame_11.png",
    "clips/sim__case_000002__fail_pick/frame_12.png",
    "clips/sim__case_000002__fail_pick/frame_13.png",
    "clips/sim__case_000002__fail_pick/frame_14.png",
    "clips/sim__case_000002__fail_pick/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__fail_pick/clip.gif"
  },
  {
   "key": "sim__case_000002__fail_move",
   "source": "Simulation",
   "title": "Sim \u00b7 dropped in transit",
   "gt_word": "drop",
   "pred_word": "drop",
   "ok": false,
   "head": "FAILURE \u00b7 DROP",
   "body": "The object slipped or was dropped during the move.",
   "conf": 0.994,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__fail_move/frame_00.png",
    "clips/sim__case_000002__fail_move/frame_01.png",
    "clips/sim__case_000002__fail_move/frame_02.png",
    "clips/sim__case_000002__fail_move/frame_03.png",
    "clips/sim__case_000002__fail_move/frame_04.png",
    "clips/sim__case_000002__fail_move/frame_05.png",
    "clips/sim__case_000002__fail_move/frame_06.png",
    "clips/sim__case_000002__fail_move/frame_07.png",
    "clips/sim__case_000002__fail_move/frame_08.png",
    "clips/sim__case_000002__fail_move/frame_09.png",
    "clips/sim__case_000002__fail_move/frame_10.png",
    "clips/sim__case_000002__fail_move/frame_11.png",
    "clips/sim__case_000002__fail_move/frame_12.png",
    "clips/sim__case_000002__fail_move/frame_13.png",
    "clips/sim__case_000002__fail_move/frame_14.png",
    "clips/sim__case_000002__fail_move/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__fail_move/clip.gif"
  },
  {
   "key": "sim__case_000002__fail_place",
   "source": "Simulation",
   "title": "Sim \u00b7 wrong placement",
   "gt_word": "place",
   "pred_word": "place",
   "ok": false,
   "head": "FAILURE \u00b7 PLACE",
   "body": "The object was released in the wrong location.",
   "conf": 0.793,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__fail_place/frame_00.png",
    "clips/sim__case_000002__fail_place/frame_01.png",
    "clips/sim__case_000002__fail_place/frame_02.png",
    "clips/sim__case_000002__fail_place/frame_03.png",
    "clips/sim__case_000002__fail_place/frame_04.png",
    "clips/sim__case_000002__fail_place/frame_05.png",
    "clips/sim__case_000002__fail_place/frame_06.png",
    "clips/sim__case_000002__fail_place/frame_07.png",
    "clips/sim__case_000002__fail_place/frame_08.png",
    "clips/sim__case_000002__fail_place/frame_09.png",
    "clips/sim__case_000002__fail_place/frame_10.png",
    "clips/sim__case_000002__fail_place/frame_11.png",
    "clips/sim__case_000002__fail_place/frame_12.png",
    "clips/sim__case_000002__fail_place/frame_13.png",
    "clips/sim__case_000002__fail_place/frame_14.png",
    "clips/sim__case_000002__fail_place/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__fail_place/clip.gif"
  },
  {
   "key": "sim__case_000002__fail_no_release",
   "source": "Simulation",
   "title": "Sim \u00b7 never released",
   "gt_word": "release",
   "pred_word": "release",
   "ok": false,
   "head": "FAILURE \u00b7 NO-RELEASE",
   "body": "The arm finished the motion but never released the object.",
   "conf": 0.995,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__fail_no_release/frame_00.png",
    "clips/sim__case_000002__fail_no_release/frame_01.png",
    "clips/sim__case_000002__fail_no_release/frame_02.png",
    "clips/sim__case_000002__fail_no_release/frame_03.png",
    "clips/sim__case_000002__fail_no_release/frame_04.png",
    "clips/sim__case_000002__fail_no_release/frame_05.png",
    "clips/sim__case_000002__fail_no_release/frame_06.png",
    "clips/sim__case_000002__fail_no_release/frame_07.png",
    "clips/sim__case_000002__fail_no_release/frame_08.png",
    "clips/sim__case_000002__fail_no_release/frame_09.png",
    "clips/sim__case_000002__fail_no_release/frame_10.png",
    "clips/sim__case_000002__fail_no_release/frame_11.png",
    "clips/sim__case_000002__fail_no_release/frame_12.png",
    "clips/sim__case_000002__fail_no_release/frame_13.png",
    "clips/sim__case_000002__fail_no_release/frame_14.png",
    "clips/sim__case_000002__fail_no_release/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__fail_no_release/clip.gif"
  },
  {
   "key": "real__ball__perfect",
   "source": "Real (target robot)",
   "title": "Real \u00b7 clean pick-and-place",
   "gt_word": "success",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.874,
   "correct": true,
   "frames": [
    "clips/real__ball__perfect/frame_00.png",
    "clips/real__ball__perfect/frame_01.png",
    "clips/real__ball__perfect/frame_02.png",
    "clips/real__ball__perfect/frame_03.png",
    "clips/real__ball__perfect/frame_04.png",
    "clips/real__ball__perfect/frame_05.png",
    "clips/real__ball__perfect/frame_06.png",
    "clips/real__ball__perfect/frame_07.png",
    "clips/real__ball__perfect/frame_08.png",
    "clips/real__ball__perfect/frame_09.png",
    "clips/real__ball__perfect/frame_10.png",
    "clips/real__ball__perfect/frame_11.png",
    "clips/real__ball__perfect/frame_12.png",
    "clips/real__ball__perfect/frame_13.png",
    "clips/real__ball__perfect/frame_14.png",
    "clips/real__ball__perfect/frame_15.png"
   ],
   "gif": "clips/real__ball__perfect/clip.gif"
  },
  {
   "key": "real__ball__fail_pick",
   "source": "Real (target robot)",
   "title": "Real \u00b7 failed pick",
   "gt_word": "pick",
   "pred_word": "pick",
   "ok": false,
   "head": "FAILURE \u00b7 PICK",
   "body": "The arm failed to pick up the object (missed or off-centre grasp).",
   "conf": 0.982,
   "correct": true,
   "frames": [
    "clips/real__ball__fail_pick/frame_00.png",
    "clips/real__ball__fail_pick/frame_01.png",
    "clips/real__ball__fail_pick/frame_02.png",
    "clips/real__ball__fail_pick/frame_03.png",
    "clips/real__ball__fail_pick/frame_04.png",
    "clips/real__ball__fail_pick/frame_05.png",
    "clips/real__ball__fail_pick/frame_06.png",
    "clips/real__ball__fail_pick/frame_07.png",
    "clips/real__ball__fail_pick/frame_08.png",
    "clips/real__ball__fail_pick/frame_09.png",
    "clips/real__ball__fail_pick/frame_10.png",
    "clips/real__ball__fail_pick/frame_11.png",
    "clips/real__ball__fail_pick/frame_12.png",
    "clips/real__ball__fail_pick/frame_13.png",
    "clips/real__ball__fail_pick/frame_14.png",
    "clips/real__ball__fail_pick/frame_15.png"
   ],
   "gif": "clips/real__ball__fail_pick/clip.gif"
  },
  {
   "key": "real__ball__fail_move",
   "source": "Real (target robot)",
   "title": "Real \u00b7 dropped in transit",
   "gt_word": "drop",
   "pred_word": "drop",
   "ok": false,
   "head": "FAILURE \u00b7 DROP",
   "body": "The object slipped or was dropped during the move.",
   "conf": 0.958,
   "correct": true,
   "frames": [
    "clips/real__ball__fail_move/frame_00.png",
    "clips/real__ball__fail_move/frame_01.png",
    "clips/real__ball__fail_move/frame_02.png",
    "clips/real__ball__fail_move/frame_03.png",
    "clips/real__ball__fail_move/frame_04.png",
    "clips/real__ball__fail_move/frame_05.png",
    "clips/real__ball__fail_move/frame_06.png",
    "clips/real__ball__fail_move/frame_07.png",
    "clips/real__ball__fail_move/frame_08.png",
    "clips/real__ball__fail_move/frame_09.png",
    "clips/real__ball__fail_move/frame_10.png",
    "clips/real__ball__fail_move/frame_11.png",
    "clips/real__ball__fail_move/frame_12.png",
    "clips/real__ball__fail_move/frame_13.png",
    "clips/real__ball__fail_move/frame_14.png",
    "clips/real__ball__fail_move/frame_15.png"
   ],
   "gif": "clips/real__ball__fail_move/clip.gif"
  },
  {
   "key": "fv__fail_move",
   "source": "OOD \u00b7 viewpoint",
   "title": "OOD viewpoint \u00b7 dropped",
   "gt_word": "drop",
   "pred_word": "drop",
   "ok": false,
   "head": "FAILURE \u00b7 DROP",
   "body": "The object slipped or was dropped during the move.",
   "conf": 0.993,
   "correct": true,
   "frames": [
    "clips/fv__fail_move/frame_00.png",
    "clips/fv__fail_move/frame_01.png",
    "clips/fv__fail_move/frame_02.png",
    "clips/fv__fail_move/frame_03.png",
    "clips/fv__fail_move/frame_04.png",
    "clips/fv__fail_move/frame_05.png",
    "clips/fv__fail_move/frame_06.png",
    "clips/fv__fail_move/frame_07.png",
    "clips/fv__fail_move/frame_08.png",
    "clips/fv__fail_move/frame_09.png",
    "clips/fv__fail_move/frame_10.png",
    "clips/fv__fail_move/frame_11.png",
    "clips/fv__fail_move/frame_12.png",
    "clips/fv__fail_move/frame_13.png",
    "clips/fv__fail_move/frame_14.png",
    "clips/fv__fail_move/frame_15.png"
   ],
   "gif": "clips/fv__fail_move/clip.gif"
  },
  {
   "key": "vfb__success",
   "source": "OOD \u00b7 cross-robot",
   "title": "OOD robot \u00b7 success",
   "gt_word": "success",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.61,
   "correct": true,
   "frames": [
    "clips/vfb__success/frame_00.png",
    "clips/vfb__success/frame_01.png",
    "clips/vfb__success/frame_02.png",
    "clips/vfb__success/frame_03.png",
    "clips/vfb__success/frame_04.png",
    "clips/vfb__success/frame_05.png",
    "clips/vfb__success/frame_06.png",
    "clips/vfb__success/frame_07.png",
    "clips/vfb__success/frame_08.png",
    "clips/vfb__success/frame_09.png",
    "clips/vfb__success/frame_10.png",
    "clips/vfb__success/frame_11.png",
    "clips/vfb__success/frame_12.png",
    "clips/vfb__success/frame_13.png",
    "clips/vfb__success/frame_14.png",
    "clips/vfb__success/frame_15.png"
   ],
   "gif": "clips/vfb__success/clip.gif"
  }
 ]
};
