window.RAFD_DATA = {
 "n_frames": 16,
 "menu": [
  "success",
  "pick",
  "drop",
  "place",
  "release"
 ],
 "clips": [
  {
   "key": "sim__case_000002__perfect",
   "source": "Simulation",
   "title": "Sim \u00b7 clean pick-and-place",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.947,
   "gt_binary": "success",
   "gt_mode": null,
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": null,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__perfect/frame_00.png",
    "clips/sim__case_000002__perfect/frame_01.png",
    "clips/sim__case_000002__perfect/frame_02.png",
    "clips/sim__case_000002__perfect/frame_03.png",
    "clips/sim__case_000002__perfect/frame_04.png",
    "clips/sim__case_000002__perfect/frame_05.png",
    "clips/sim__case_000002__perfect/frame_06.png",
    "clips/sim__case_000002__perfect/frame_07.png",
    "clips/sim__case_000002__perfect/frame_08.png",
    "clips/sim__case_000002__perfect/frame_09.png",
    "clips/sim__case_000002__perfect/frame_10.png",
    "clips/sim__case_000002__perfect/frame_11.png",
    "clips/sim__case_000002__perfect/frame_12.png",
    "clips/sim__case_000002__perfect/frame_13.png",
    "clips/sim__case_000002__perfect/frame_14.png",
    "clips/sim__case_000002__perfect/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__perfect/clip.gif"
  },
  {
   "key": "sim__case_000002__fail_pick",
   "source": "Simulation",
   "title": "Sim \u00b7 failed pick",
   "pred_word": "pick",
   "ok": false,
   "head": "FAILURE \u00b7 PICK",
   "body": "The arm failed to pick up the object (missed or off-centre grasp).",
   "conf": 0.992,
   "gt_binary": "failure",
   "gt_mode": "pick",
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": true,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__fail_pick/frame_00.png",
    "clips/sim__case_000002__fail_pick/frame_01.png",
    "clips/sim__case_000002__fail_pick/frame_02.png",
    "clips/sim__case_000002__fail_pick/frame_03.png",
    "clips/sim__case_000002__fail_pick/frame_04.png",
    "clips/sim__case_000002__fail_pick/frame_05.png",
    "clips/sim__case_000002__fail_pick/frame_06.png",
    "clips/sim__case_000002__fail_pick/frame_07.png",
    "clips/sim__case_000002__fail_pick/frame_08.png",
    "clips/sim__case_000002__fail_pick/frame_09.png",
    "clips/sim__case_000002__fail_pick/frame_10.png",
    "clips/sim__case_000002__fail_pick/frame_11.png",
    "clips/sim__case_000002__fail_pick/frame_12.png",
    "clips/sim__case_000002__fail_pick/frame_13.png",
    "clips/sim__case_000002__fail_pick/frame_14.png",
    "clips/sim__case_000002__fail_pick/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__fail_pick/clip.gif"
  },
  {
   "key": "sim__case_000002__fail_move",
   "source": "Simulation",
   "title": "Sim \u00b7 dropped in transit",
   "pred_word": "drop",
   "ok": false,
   "head": "FAILURE \u00b7 DROP",
   "body": "The object slipped or was dropped during the move.",
   "conf": 0.994,
   "gt_binary": "failure",
   "gt_mode": "drop",
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": true,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__fail_move/frame_00.png",
    "clips/sim__case_000002__fail_move/frame_01.png",
    "clips/sim__case_000002__fail_move/frame_02.png",
    "clips/sim__case_000002__fail_move/frame_03.png",
    "clips/sim__case_000002__fail_move/frame_04.png",
    "clips/sim__case_000002__fail_move/frame_05.png",
    "clips/sim__case_000002__fail_move/frame_06.png",
    "clips/sim__case_000002__fail_move/frame_07.png",
    "clips/sim__case_000002__fail_move/frame_08.png",
    "clips/sim__case_000002__fail_move/frame_09.png",
    "clips/sim__case_000002__fail_move/frame_10.png",
    "clips/sim__case_000002__fail_move/frame_11.png",
    "clips/sim__case_000002__fail_move/frame_12.png",
    "clips/sim__case_000002__fail_move/frame_13.png",
    "clips/sim__case_000002__fail_move/frame_14.png",
    "clips/sim__case_000002__fail_move/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__fail_move/clip.gif"
  },
  {
   "key": "sim__case_000002__fail_place",
   "source": "Simulation",
   "title": "Sim \u00b7 wrong placement",
   "pred_word": "place",
   "ok": false,
   "head": "FAILURE \u00b7 PLACE",
   "body": "During placing the arm pressed down with too much force, so the object was not set down properly.",
   "conf": 0.793,
   "gt_binary": "failure",
   "gt_mode": "place",
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": true,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__fail_place/frame_00.png",
    "clips/sim__case_000002__fail_place/frame_01.png",
    "clips/sim__case_000002__fail_place/frame_02.png",
    "clips/sim__case_000002__fail_place/frame_03.png",
    "clips/sim__case_000002__fail_place/frame_04.png",
    "clips/sim__case_000002__fail_place/frame_05.png",
    "clips/sim__case_000002__fail_place/frame_06.png",
    "clips/sim__case_000002__fail_place/frame_07.png",
    "clips/sim__case_000002__fail_place/frame_08.png",
    "clips/sim__case_000002__fail_place/frame_09.png",
    "clips/sim__case_000002__fail_place/frame_10.png",
    "clips/sim__case_000002__fail_place/frame_11.png",
    "clips/sim__case_000002__fail_place/frame_12.png",
    "clips/sim__case_000002__fail_place/frame_13.png",
    "clips/sim__case_000002__fail_place/frame_14.png",
    "clips/sim__case_000002__fail_place/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__fail_place/clip.gif"
  },
  {
   "key": "sim__case_000002__fail_no_release",
   "source": "Simulation",
   "title": "Sim \u00b7 never released",
   "pred_word": "release",
   "ok": false,
   "head": "FAILURE \u00b7 NO-RELEASE",
   "body": "The arm finished the motion but never released the object.",
   "conf": 0.995,
   "gt_binary": "failure",
   "gt_mode": "release",
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": true,
   "correct": true,
   "frames": [
    "clips/sim__case_000002__fail_no_release/frame_00.png",
    "clips/sim__case_000002__fail_no_release/frame_01.png",
    "clips/sim__case_000002__fail_no_release/frame_02.png",
    "clips/sim__case_000002__fail_no_release/frame_03.png",
    "clips/sim__case_000002__fail_no_release/frame_04.png",
    "clips/sim__case_000002__fail_no_release/frame_05.png",
    "clips/sim__case_000002__fail_no_release/frame_06.png",
    "clips/sim__case_000002__fail_no_release/frame_07.png",
    "clips/sim__case_000002__fail_no_release/frame_08.png",
    "clips/sim__case_000002__fail_no_release/frame_09.png",
    "clips/sim__case_000002__fail_no_release/frame_10.png",
    "clips/sim__case_000002__fail_no_release/frame_11.png",
    "clips/sim__case_000002__fail_no_release/frame_12.png",
    "clips/sim__case_000002__fail_no_release/frame_13.png",
    "clips/sim__case_000002__fail_no_release/frame_14.png",
    "clips/sim__case_000002__fail_no_release/frame_15.png"
   ],
   "gif": "clips/sim__case_000002__fail_no_release/clip.gif"
  },
  {
   "key": "real__ball__perfect",
   "source": "Real (target robot)",
   "title": "Real \u00b7 clean pick-and-place",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.874,
   "gt_binary": "success",
   "gt_mode": null,
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": null,
   "correct": true,
   "frames": [
    "clips/real__ball__perfect/frame_00.png",
    "clips/real__ball__perfect/frame_01.png",
    "clips/real__ball__perfect/frame_02.png",
    "clips/real__ball__perfect/frame_03.png",
    "clips/real__ball__perfect/frame_04.png",
    "clips/real__ball__perfect/frame_05.png",
    "clips/real__ball__perfect/frame_06.png",
    "clips/real__ball__perfect/frame_07.png",
    "clips/real__ball__perfect/frame_08.png",
    "clips/real__ball__perfect/frame_09.png",
    "clips/real__ball__perfect/frame_10.png",
    "clips/real__ball__perfect/frame_11.png",
    "clips/real__ball__perfect/frame_12.png",
    "clips/real__ball__perfect/frame_13.png",
    "clips/real__ball__perfect/frame_14.png",
    "clips/real__ball__perfect/frame_15.png"
   ],
   "gif": "clips/real__ball__perfect/clip.gif"
  },
  {
   "key": "real__ball__fail_pick",
   "source": "Real (target robot)",
   "title": "Real \u00b7 failed pick",
   "pred_word": "pick",
   "ok": false,
   "head": "FAILURE \u00b7 PICK",
   "body": "The arm failed to pick up the object (missed or off-centre grasp).",
   "conf": 0.982,
   "gt_binary": "failure",
   "gt_mode": "pick",
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": true,
   "correct": true,
   "frames": [
    "clips/real__ball__fail_pick/frame_00.png",
    "clips/real__ball__fail_pick/frame_01.png",
    "clips/real__ball__fail_pick/frame_02.png",
    "clips/real__ball__fail_pick/frame_03.png",
    "clips/real__ball__fail_pick/frame_04.png",
    "clips/real__ball__fail_pick/frame_05.png",
    "clips/real__ball__fail_pick/frame_06.png",
    "clips/real__ball__fail_pick/frame_07.png",
    "clips/real__ball__fail_pick/frame_08.png",
    "clips/real__ball__fail_pick/frame_09.png",
    "clips/real__ball__fail_pick/frame_10.png",
    "clips/real__ball__fail_pick/frame_11.png",
    "clips/real__ball__fail_pick/frame_12.png",
    "clips/real__ball__fail_pick/frame_13.png",
    "clips/real__ball__fail_pick/frame_14.png",
    "clips/real__ball__fail_pick/frame_15.png"
   ],
   "gif": "clips/real__ball__fail_pick/clip.gif"
  },
  {
   "key": "real__ball__fail_move",
   "source": "Real (target robot)",
   "title": "Real \u00b7 dropped in transit",
   "pred_word": "drop",
   "ok": false,
   "head": "FAILURE \u00b7 DROP",
   "body": "The object slipped or was dropped during the move.",
   "conf": 0.958,
   "gt_binary": "failure",
   "gt_mode": "drop",
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": true,
   "correct": true,
   "frames": [
    "clips/real__ball__fail_move/frame_00.png",
    "clips/real__ball__fail_move/frame_01.png",
    "clips/real__ball__fail_move/frame_02.png",
    "clips/real__ball__fail_move/frame_03.png",
    "clips/real__ball__fail_move/frame_04.png",
    "clips/real__ball__fail_move/frame_05.png",
    "clips/real__ball__fail_move/frame_06.png",
    "clips/real__ball__fail_move/frame_07.png",
    "clips/real__ball__fail_move/frame_08.png",
    "clips/real__ball__fail_move/frame_09.png",
    "clips/real__ball__fail_move/frame_10.png",
    "clips/real__ball__fail_move/frame_11.png",
    "clips/real__ball__fail_move/frame_12.png",
    "clips/real__ball__fail_move/frame_13.png",
    "clips/real__ball__fail_move/frame_14.png",
    "clips/real__ball__fail_move/frame_15.png"
   ],
   "gif": "clips/real__ball__fail_move/clip.gif"
  },
  {
   "key": "fv__perfect",
   "source": "OOD \u00b7 viewpoint",
   "title": "OOD viewpoint \u00b7 success",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.536,
   "gt_binary": "success",
   "gt_mode": null,
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": null,
   "correct": true,
   "frames": [
    "clips/fv__perfect/frame_00.png",
    "clips/fv__perfect/frame_01.png",
    "clips/fv__perfect/frame_02.png",
    "clips/fv__perfect/frame_03.png",
    "clips/fv__perfect/frame_04.png",
    "clips/fv__perfect/frame_05.png",
    "clips/fv__perfect/frame_06.png",
    "clips/fv__perfect/frame_07.png",
    "clips/fv__perfect/frame_08.png",
    "clips/fv__perfect/frame_09.png",
    "clips/fv__perfect/frame_10.png",
    "clips/fv__perfect/frame_11.png",
    "clips/fv__perfect/frame_12.png",
    "clips/fv__perfect/frame_13.png",
    "clips/fv__perfect/frame_14.png",
    "clips/fv__perfect/frame_15.png"
   ],
   "gif": "clips/fv__perfect/clip.gif"
  },
  {
   "key": "vfb__success",
   "source": "OOD \u00b7 cross-robot",
   "title": "OOD robot \u00b7 success",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.61,
   "gt_binary": "success",
   "gt_mode": null,
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": null,
   "correct": true,
   "frames": [
    "clips/vfb__success/frame_00.png",
    "clips/vfb__success/frame_01.png",
    "clips/vfb__success/frame_02.png",
    "clips/vfb__success/frame_03.png",
    "clips/vfb__success/frame_04.png",
    "clips/vfb__success/frame_05.png",
    "clips/vfb__success/frame_06.png",
    "clips/vfb__success/frame_07.png",
    "clips/vfb__success/frame_08.png",
    "clips/vfb__success/frame_09.png",
    "clips/vfb__success/frame_10.png",
    "clips/vfb__success/frame_11.png",
    "clips/vfb__success/frame_12.png",
    "clips/vfb__success/frame_13.png",
    "clips/vfb__success/frame_14.png",
    "clips/vfb__success/frame_15.png"
   ],
   "gif": "clips/vfb__success/clip.gif"
  },
  {
   "key": "vfb__fail_move",
   "source": "OOD \u00b7 cross-robot",
   "title": "OOD robot \u00b7 dropped (mode hard)",
   "pred_word": "pick",
   "ok": false,
   "head": "FAILURE \u00b7 PICK",
   "body": "The arm failed to pick up the object (missed or off-centre grasp).",
   "conf": 0.917,
   "gt_binary": "failure",
   "gt_mode": "drop",
   "binary_only": false,
   "binary_correct": true,
   "mode_correct": false,
   "correct": false,
   "frames": [
    "clips/vfb__fail_move/frame_00.png",
    "clips/vfb__fail_move/frame_01.png",
    "clips/vfb__fail_move/frame_02.png",
    "clips/vfb__fail_move/frame_03.png",
    "clips/vfb__fail_move/frame_04.png",
    "clips/vfb__fail_move/frame_05.png",
    "clips/vfb__fail_move/frame_06.png",
    "clips/vfb__fail_move/frame_07.png",
    "clips/vfb__fail_move/frame_08.png",
    "clips/vfb__fail_move/frame_09.png",
    "clips/vfb__fail_move/frame_10.png",
    "clips/vfb__fail_move/frame_11.png",
    "clips/vfb__fail_move/frame_12.png",
    "clips/vfb__fail_move/frame_13.png",
    "clips/vfb__fail_move/frame_14.png",
    "clips/vfb__fail_move/frame_15.png"
   ],
   "gif": "clips/vfb__fail_move/clip.gif"
  },
  {
   "key": "ff__rlbench_ok",
   "source": "Far-OOD",
   "title": "Far-OOD \u00b7 RLBench (close box)",
   "pred_word": "pick",
   "ok": false,
   "head": "FAILURE \u00b7 PICK",
   "body": "The arm failed to pick up the object (missed or off-centre grasp).",
   "conf": 0.947,
   "gt_binary": "success",
   "gt_mode": null,
   "binary_only": true,
   "binary_correct": false,
   "mode_correct": null,
   "correct": false,
   "frames": [
    "clips/ff__rlbench_ok/frame_00.png",
    "clips/ff__rlbench_ok/frame_01.png",
    "clips/ff__rlbench_ok/frame_02.png",
    "clips/ff__rlbench_ok/frame_03.png",
    "clips/ff__rlbench_ok/frame_04.png",
    "clips/ff__rlbench_ok/frame_05.png",
    "clips/ff__rlbench_ok/frame_06.png",
    "clips/ff__rlbench_ok/frame_07.png",
    "clips/ff__rlbench_ok/frame_08.png",
    "clips/ff__rlbench_ok/frame_09.png",
    "clips/ff__rlbench_ok/frame_10.png",
    "clips/ff__rlbench_ok/frame_11.png",
    "clips/ff__rlbench_ok/frame_12.png",
    "clips/ff__rlbench_ok/frame_13.png",
    "clips/ff__rlbench_ok/frame_14.png",
    "clips/ff__rlbench_ok/frame_15.png"
   ],
   "gif": "clips/ff__rlbench_ok/clip.gif"
  },
  {
   "key": "ff__rlbench_fail",
   "source": "Far-OOD",
   "title": "Far-OOD \u00b7 RLBench (failed task)",
   "pred_word": "pick",
   "ok": false,
   "head": "FAILURE \u00b7 PICK",
   "body": "The arm failed to pick up the object (missed or off-centre grasp).",
   "conf": 0.912,
   "gt_binary": "failure",
   "gt_mode": null,
   "binary_only": true,
   "binary_correct": true,
   "mode_correct": null,
   "correct": true,
   "frames": [
    "clips/ff__rlbench_fail/frame_00.png",
    "clips/ff__rlbench_fail/frame_01.png",
    "clips/ff__rlbench_fail/frame_02.png",
    "clips/ff__rlbench_fail/frame_03.png",
    "clips/ff__rlbench_fail/frame_04.png",
    "clips/ff__rlbench_fail/frame_05.png",
    "clips/ff__rlbench_fail/frame_06.png",
    "clips/ff__rlbench_fail/frame_07.png",
    "clips/ff__rlbench_fail/frame_08.png",
    "clips/ff__rlbench_fail/frame_09.png",
    "clips/ff__rlbench_fail/frame_10.png",
    "clips/ff__rlbench_fail/frame_11.png",
    "clips/ff__rlbench_fail/frame_12.png",
    "clips/ff__rlbench_fail/frame_13.png",
    "clips/ff__rlbench_fail/frame_14.png",
    "clips/ff__rlbench_fail/frame_15.png"
   ],
   "gif": "clips/ff__rlbench_fail/clip.gif"
  },
  {
   "key": "ff__robofac_fail",
   "source": "Far-OOD",
   "title": "Far-OOD \u00b7 RoboFAC (failed task)",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.546,
   "gt_binary": "failure",
   "gt_mode": null,
   "binary_only": true,
   "binary_correct": false,
   "mode_correct": null,
   "correct": false,
   "frames": [
    "clips/ff__robofac_fail/frame_00.png",
    "clips/ff__robofac_fail/frame_01.png",
    "clips/ff__robofac_fail/frame_02.png",
    "clips/ff__robofac_fail/frame_03.png",
    "clips/ff__robofac_fail/frame_04.png",
    "clips/ff__robofac_fail/frame_05.png",
    "clips/ff__robofac_fail/frame_06.png",
    "clips/ff__robofac_fail/frame_07.png",
    "clips/ff__robofac_fail/frame_08.png",
    "clips/ff__robofac_fail/frame_09.png",
    "clips/ff__robofac_fail/frame_10.png",
    "clips/ff__robofac_fail/frame_11.png",
    "clips/ff__robofac_fail/frame_12.png",
    "clips/ff__robofac_fail/frame_13.png",
    "clips/ff__robofac_fail/frame_14.png",
    "clips/ff__robofac_fail/frame_15.png"
   ],
   "gif": "clips/ff__robofac_fail/clip.gif"
  },
  {
   "key": "berkeley__ok",
   "source": "OOD \u00b7 UR5 (success probe)",
   "title": "OOD UR5 \u00b7 success (no mode)",
   "pred_word": "success",
   "ok": true,
   "head": "SUCCESS",
   "body": "The arm picked the object and placed it correctly.",
   "conf": 0.808,
   "gt_binary": "success",
   "gt_mode": null,
   "binary_only": true,
   "binary_correct": true,
   "mode_correct": null,
   "correct": true,
   "frames": [
    "clips/berkeley__ok/frame_00.png",
    "clips/berkeley__ok/frame_01.png",
    "clips/berkeley__ok/frame_02.png",
    "clips/berkeley__ok/frame_03.png",
    "clips/berkeley__ok/frame_04.png",
    "clips/berkeley__ok/frame_05.png",
    "clips/berkeley__ok/frame_06.png",
    "clips/berkeley__ok/frame_07.png",
    "clips/berkeley__ok/frame_08.png",
    "clips/berkeley__ok/frame_09.png",
    "clips/berkeley__ok/frame_10.png",
    "clips/berkeley__ok/frame_11.png",
    "clips/berkeley__ok/frame_12.png",
    "clips/berkeley__ok/frame_13.png",
    "clips/berkeley__ok/frame_14.png",
    "clips/berkeley__ok/frame_15.png"
   ],
   "gif": "clips/berkeley__ok/clip.gif"
  }
 ]
};
